version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  deploy-staging:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install nasm python-dev libpng-dev python-pip build-essential libpython-dev
            pip install awsebcli --upgrade --user
      - run: 
          name: Build
          command: yarn && yarn build:staging
      - run:
          name: AWS credentials
          command: |
            mkdir ~/.aws
            echo "[eb-cli]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
      - run:
          name: Deploy
          command: ~/.local/bin/eb deploy pop-consultation-staging
workflows:
  version: 2
  test-then-deploy:
    jobs:
      - test
      - deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: master
